version: "3.8"

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: clockregister
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    hostname: clockregister.com.br
    volumes:
      - ./client/:/usr/src/app
    ports:
      - '5173:5173'