name: GitHub Action Java CI/CD with Maven and PostgreSQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: clockregister
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Maven version
        run: mvn --version

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
          maven-version: '3.11.0'

      - name: Build with Maven and run tests
        run: mvn clean install -Ddb.url=jdbc:postgresql://localhost:5432/clockregister -Ddb.username=postgres -Ddb.password=admin
