name: GitHub Action Java CI/CD with Maven and PostgreSQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: clockregister
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          distribution: 'adopt'
          cache: maven

      - name: Wait for PostgreSQL
        run: |
          timeout=300
          until docker run --network=host postgres:latest pg_isready; do
            timeout=$((timeout-1))
            if [ $timeout -eq 0 ]; then
              echo "PostgreSQL did not start in time."
              exit 1
            fi
            sleep 1
          done

      - name: Build with Maven and run tests
        run: mvn clean install -Ddb.url=jdbc:postgresql://localhost:5432/clockregister -Ddb.username=postgres -Ddb.password=admin
